name: life_quest
description: A gamified life goals app built with Flutter and Supabase

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  # State Management
  flutter_riverpod: ^2.3.6

  # Supabase
  supabase_flutter: ^2.8.4

  # Analytics
  posthog_flutter: ^4.0.1

  # UI Components
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  lottie: ^3.3.1
  flutter_animate: ^4.5.2

  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.1.12
  shared_preferences: ^2.2.0
  path_provider: ^2.0.15
  flutter_secure_storage: ^10.0.0-beta.4
  connectivity_plus: ^6.1.3
  logger: ^2.5.0
  uuid: ^4.5.1

  # Phone Auth
  phone_number: ^2.0.1
  pin_code_fields: ^8.0.1

  google_sign_in: ^6.1.4
  sign_in_with_apple: ^6.1.4
  crypto: ^3.0.3
  flutter_dotenv: ^5.2.1
  image_picker: ^1.0.4
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 23 # android min sdk min:16, default 23
  macos:
    generate: true
    image_path: "assets/icon/icon.png"