name: life_quest
description: A gamified life goals app built with Flutter and Supabase

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5

  # State Management
  flutter_riverpod: ^2.3.6

  # Supabase
  supabase_flutter: ^1.10.14

  # Analytics
  posthog_flutter: ^4.0.1

  # UI Components
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  flutter_animate: ^4.5.2

  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.1.12
  shared_preferences: ^2.2.0
  path_provider: ^2.0.15
  flutter_secure_storage: ^8.0.0
  connectivity_plus: ^4.0.2
  logger: ^1.4.0
  uuid: ^3.0.7

  # Phone Auth
  phone_number: ^2.0.1
  pin_code_fields: ^8.0.1

  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  mocktail: ^0.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700